version: '3'

services:
  kenamobile_restapi:
    image: matt0550/kenamobile_restapi
    environment:
      - PUID=1000     # UID of the user inside the container
      - PGID=1000     # GID of the user inside the container
    ports:
      - 7013:5000
    restart: unless-stopped
